spring.application.name=aprimore
spring.config.import=optional:file:.env[.properties]
server.port=${PORT:8080}

# Configuracao MySQL
spring.jpa.hibernate.ddl-auto=update
# spring.datasource.url=jdbc:mysql://localhost:3306/${DB_NAME}
# spring.datasource.username=${DB_USER}
# spring.datasource.password=${DB_PASS}
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracao H2 em memoria
spring.datasource.url=jdbc:h2:mem:aprimore;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=USER
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.show-sql: true

spring.mail.host=${SMTP_HOST:localhost}
spring.mail.port=${SMTP_PORT:25}
spring.mail.username=${EMAIL:}
spring.mail.password=${SMTP_PASS:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.base-url=${APP_BASE_URL:http://localhost:8080}

main.name=${MAIN_NAME:Administrador Principal}
main.email=${MAIN_EMAIL:admin@example.com}
main.pass=${MAIN_PASS:change-me}
